language: r

cache: packages
dist: bionic
os: linux

warnings_are_errors: false

r_packages:
  - testthat
  - MASS
  - utils
  
before_deploy:
  - R -e "install.packages('roxygen2', repos = 'http://cran.rstudio.com')"

notifications:
  email:
    on_success: change
    on_failure: change
